seed: 0

env:
  max_steps: 100
  scenario_name: "repeat_last"
  scenario:
    n_agents: 4
    k: 4
    horizon: 100
  device: ??? # These values will be populated dynamically
  vmas_envs: ???

model:
  shared_parameters: True
  centralised_critic: True  # MAPPO if True, IPPO if False
  use_rnn: True

collector:
  frames_per_batch: 40_000 # Frames sampled each sampling iteration
  n_iters: 500 # Number of sampling/training iterations
  total_frames: ???

buffer:
  memory_size: ???

loss:
  gamma: 0.99
  lmbda: 0.9
  entropy_eps: 0.1
  clip_epsilon: 0.2

train:
  num_epochs: 45  # optimization steps per batch of data collected
  minibatch_size: 4000 # size of minibatches used in each epoch
  lr: 5e-5
  max_grad_norm: 40.0
  device: ???

eval:
  evaluation_interval: 20
  evaluation_episodes: 200

logger:
  backend:  # Delete to remove logging
  project_name: null
  group_name: null
